version: '2'

services:

  vote:
    labels:
      HAPROXY_GROUP: "external"
      HAPROXY_0_VHOST: "vote.dev.gbm.digital"
      HAPROXY_0_MODE: "http"

  result:
    labels:
      HAPROXY_GROUP: "external"
      HAPROXY_0_VHOST: "result.dev.gbm.digital"
      HAPROXY_0_MODE: "http"