version: "2"

services:
  vote:
    build: ./vote
    command: python app.py
    ports:
      - "5000:80"

  result:
    build: ./result
    command: nodemon --debug server.js
    ports:
      - "5001:80"

  worker:
    build: ./worker

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]

  db:
    image: postgres:9.4
    container_name: db